/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/components/atoms/AppLogo.vue')['default']
    BaseButton: typeof import('./src/components/atoms/BaseButton.vue')['default']
    BrandingPanel: typeof import('./src/components/organisms/BrandingPanel.vue')['default']
    Button: typeof import('primevue/button')['default']
    FormField: typeof import('./src/components/atoms/FormField.vue')['default']
    GroupCard: typeof import('./src/components/molecules/GroupCard.vue')['default']
    GroupList: typeof import('./src/components/organisms/GroupList.vue')['default']
    GroupSearchPanel: typeof import('./src/components/organisms/GroupSearchPanel.vue')['default']
    LinkField: typeof import('./src/components/atoms/LinkField.vue')['default']
    LoginForm: typeof import('./src/components/molecules/LoginForm.vue')['default']
    LoginPanel: typeof import('./src/components/organisms/LoginPanel.vue')['default']
    MultipleListBoxField: typeof import('./src/components/atoms/MultipleListBoxField.vue')['default']
    OTPFormField: typeof import('./src/components/atoms/OTPFormField.vue')['default']
    OtpRedirectDialog: typeof import('./src/components/atoms/OtpRedirectDialog.vue')['default']
    OtpValidateForm: typeof import('./src/components/molecules/OtpValidateForm.vue')['default']
    OTPValidatePanel: typeof import('./src/components/organisms/OTPValidatePanel.vue')['default']
    PasswordRecoveryRequestForm: typeof import('./src/components/molecules/PasswordRecoveryRequestForm.vue')['default']
    RegisterForm: typeof import('./src/components/molecules/RegisterForm.vue')['default']
    RegisterPanel: typeof import('./src/components/organisms/RegisterPanel.vue')['default']
    RegisterStepperForm: typeof import('./src/components/molecules/RegisterStepperForm.vue')['default']
    RequestPasswordPanel: typeof import('./src/components/organisms/RequestPasswordPanel.vue')['default']
    ResetPasswordForm: typeof import('./src/components/molecules/ResetPasswordForm.vue')['default']
    ResetPasswordPanel: typeof import('./src/components/organisms/ResetPasswordPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectBoxField: typeof import('./src/components/atoms/SelectBoxField.vue')['default']
    UserProfileHeader: typeof import('./src/components/organisms/UserProfileHeader.vue')['default']
  }
}
